/**
 * @fileoverview gRPC-Web generated client stub for realestate
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: real_estate.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.realestate = require('./real_estate_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.realestate.RealEstateServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.realestate.RealEstateServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.realestate.Empty,
 *   !proto.realestate.Property>}
 */
const methodDescriptor_RealEstateService_StreamPropertyListings = new grpc.web.MethodDescriptor(
  '/realestate.RealEstateService/StreamPropertyListings',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.realestate.Empty,
  proto.realestate.Property,
  /**
   * @param {!proto.realestate.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.realestate.Property.deserializeBinary
);


/**
 * @param {!proto.realestate.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.realestate.Property>}
 *     The XHR Node Readable Stream
 */
proto.realestate.RealEstateServiceClient.prototype.streamPropertyListings =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/realestate.RealEstateService/StreamPropertyListings',
      request,
      metadata || {},
      methodDescriptor_RealEstateService_StreamPropertyListings);
};


/**
 * @param {!proto.realestate.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.realestate.Property>}
 *     The XHR Node Readable Stream
 */
proto.realestate.RealEstateServicePromiseClient.prototype.streamPropertyListings =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/realestate.RealEstateService/StreamPropertyListings',
      request,
      metadata || {},
      methodDescriptor_RealEstateService_StreamPropertyListings);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.realestate.Empty,
 *   !proto.realestate.PropertyUpdate>}
 */
const methodDescriptor_RealEstateService_StreamPropertyUpdates = new grpc.web.MethodDescriptor(
  '/realestate.RealEstateService/StreamPropertyUpdates',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.realestate.Empty,
  proto.realestate.PropertyUpdate,
  /**
   * @param {!proto.realestate.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.realestate.PropertyUpdate.deserializeBinary
);


/**
 * @param {!proto.realestate.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.realestate.PropertyUpdate>}
 *     The XHR Node Readable Stream
 */
proto.realestate.RealEstateServiceClient.prototype.streamPropertyUpdates =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/realestate.RealEstateService/StreamPropertyUpdates',
      request,
      metadata || {},
      methodDescriptor_RealEstateService_StreamPropertyUpdates);
};


/**
 * @param {!proto.realestate.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.realestate.PropertyUpdate>}
 *     The XHR Node Readable Stream
 */
proto.realestate.RealEstateServicePromiseClient.prototype.streamPropertyUpdates =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/realestate.RealEstateService/StreamPropertyUpdates',
      request,
      metadata || {},
      methodDescriptor_RealEstateService_StreamPropertyUpdates);
};


module.exports = proto.realestate;

