// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: real_estate.proto
#ifndef GRPC_real_5festate_2eproto__INCLUDED
#define GRPC_real_5festate_2eproto__INCLUDED

#include "real_estate.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace realestate {

class RealEstateService final {
 public:
  static constexpr char const* service_full_name() {
    return "realestate.RealEstateService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::realestate::Property>> StreamPropertyListings(::grpc::ClientContext* context, const ::realestate::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::realestate::Property>>(StreamPropertyListingsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::realestate::Property>> AsyncStreamPropertyListings(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::realestate::Property>>(AsyncStreamPropertyListingsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::realestate::Property>> PrepareAsyncStreamPropertyListings(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::realestate::Property>>(PrepareAsyncStreamPropertyListingsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::realestate::PropertyUpdate>> StreamPropertyUpdates(::grpc::ClientContext* context, const ::realestate::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::realestate::PropertyUpdate>>(StreamPropertyUpdatesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::realestate::PropertyUpdate>> AsyncStreamPropertyUpdates(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::realestate::PropertyUpdate>>(AsyncStreamPropertyUpdatesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::realestate::PropertyUpdate>> PrepareAsyncStreamPropertyUpdates(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::realestate::PropertyUpdate>>(PrepareAsyncStreamPropertyUpdatesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void StreamPropertyListings(::grpc::ClientContext* context, const ::realestate::Empty* request, ::grpc::ClientReadReactor< ::realestate::Property>* reactor) = 0;
      virtual void StreamPropertyUpdates(::grpc::ClientContext* context, const ::realestate::Empty* request, ::grpc::ClientReadReactor< ::realestate::PropertyUpdate>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::realestate::Property>* StreamPropertyListingsRaw(::grpc::ClientContext* context, const ::realestate::Empty& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::realestate::Property>* AsyncStreamPropertyListingsRaw(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::realestate::Property>* PrepareAsyncStreamPropertyListingsRaw(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::realestate::PropertyUpdate>* StreamPropertyUpdatesRaw(::grpc::ClientContext* context, const ::realestate::Empty& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::realestate::PropertyUpdate>* AsyncStreamPropertyUpdatesRaw(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::realestate::PropertyUpdate>* PrepareAsyncStreamPropertyUpdatesRaw(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::realestate::Property>> StreamPropertyListings(::grpc::ClientContext* context, const ::realestate::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::realestate::Property>>(StreamPropertyListingsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::realestate::Property>> AsyncStreamPropertyListings(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::realestate::Property>>(AsyncStreamPropertyListingsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::realestate::Property>> PrepareAsyncStreamPropertyListings(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::realestate::Property>>(PrepareAsyncStreamPropertyListingsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::realestate::PropertyUpdate>> StreamPropertyUpdates(::grpc::ClientContext* context, const ::realestate::Empty& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::realestate::PropertyUpdate>>(StreamPropertyUpdatesRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::realestate::PropertyUpdate>> AsyncStreamPropertyUpdates(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::realestate::PropertyUpdate>>(AsyncStreamPropertyUpdatesRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::realestate::PropertyUpdate>> PrepareAsyncStreamPropertyUpdates(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::realestate::PropertyUpdate>>(PrepareAsyncStreamPropertyUpdatesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void StreamPropertyListings(::grpc::ClientContext* context, const ::realestate::Empty* request, ::grpc::ClientReadReactor< ::realestate::Property>* reactor) override;
      void StreamPropertyUpdates(::grpc::ClientContext* context, const ::realestate::Empty* request, ::grpc::ClientReadReactor< ::realestate::PropertyUpdate>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::realestate::Property>* StreamPropertyListingsRaw(::grpc::ClientContext* context, const ::realestate::Empty& request) override;
    ::grpc::ClientAsyncReader< ::realestate::Property>* AsyncStreamPropertyListingsRaw(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::realestate::Property>* PrepareAsyncStreamPropertyListingsRaw(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::realestate::PropertyUpdate>* StreamPropertyUpdatesRaw(::grpc::ClientContext* context, const ::realestate::Empty& request) override;
    ::grpc::ClientAsyncReader< ::realestate::PropertyUpdate>* AsyncStreamPropertyUpdatesRaw(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::realestate::PropertyUpdate>* PrepareAsyncStreamPropertyUpdatesRaw(::grpc::ClientContext* context, const ::realestate::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_StreamPropertyListings_;
    const ::grpc::internal::RpcMethod rpcmethod_StreamPropertyUpdates_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status StreamPropertyListings(::grpc::ServerContext* context, const ::realestate::Empty* request, ::grpc::ServerWriter< ::realestate::Property>* writer);
    virtual ::grpc::Status StreamPropertyUpdates(::grpc::ServerContext* context, const ::realestate::Empty* request, ::grpc::ServerWriter< ::realestate::PropertyUpdate>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamPropertyListings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamPropertyListings() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_StreamPropertyListings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPropertyListings(::grpc::ServerContext* /*context*/, const ::realestate::Empty* /*request*/, ::grpc::ServerWriter< ::realestate::Property>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamPropertyListings(::grpc::ServerContext* context, ::realestate::Empty* request, ::grpc::ServerAsyncWriter< ::realestate::Property>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_StreamPropertyUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_StreamPropertyUpdates() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_StreamPropertyUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPropertyUpdates(::grpc::ServerContext* /*context*/, const ::realestate::Empty* /*request*/, ::grpc::ServerWriter< ::realestate::PropertyUpdate>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamPropertyUpdates(::grpc::ServerContext* context, ::realestate::Empty* request, ::grpc::ServerAsyncWriter< ::realestate::PropertyUpdate>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_StreamPropertyListings<WithAsyncMethod_StreamPropertyUpdates<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_StreamPropertyListings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamPropertyListings() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::realestate::Empty, ::realestate::Property>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::realestate::Empty* request) { return this->StreamPropertyListings(context, request); }));
    }
    ~WithCallbackMethod_StreamPropertyListings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPropertyListings(::grpc::ServerContext* /*context*/, const ::realestate::Empty* /*request*/, ::grpc::ServerWriter< ::realestate::Property>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::realestate::Property>* StreamPropertyListings(
      ::grpc::CallbackServerContext* /*context*/, const ::realestate::Empty* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_StreamPropertyUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_StreamPropertyUpdates() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::realestate::Empty, ::realestate::PropertyUpdate>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::realestate::Empty* request) { return this->StreamPropertyUpdates(context, request); }));
    }
    ~WithCallbackMethod_StreamPropertyUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPropertyUpdates(::grpc::ServerContext* /*context*/, const ::realestate::Empty* /*request*/, ::grpc::ServerWriter< ::realestate::PropertyUpdate>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::realestate::PropertyUpdate>* StreamPropertyUpdates(
      ::grpc::CallbackServerContext* /*context*/, const ::realestate::Empty* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_StreamPropertyListings<WithCallbackMethod_StreamPropertyUpdates<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_StreamPropertyListings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamPropertyListings() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_StreamPropertyListings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPropertyListings(::grpc::ServerContext* /*context*/, const ::realestate::Empty* /*request*/, ::grpc::ServerWriter< ::realestate::Property>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_StreamPropertyUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_StreamPropertyUpdates() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_StreamPropertyUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPropertyUpdates(::grpc::ServerContext* /*context*/, const ::realestate::Empty* /*request*/, ::grpc::ServerWriter< ::realestate::PropertyUpdate>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamPropertyListings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamPropertyListings() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_StreamPropertyListings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPropertyListings(::grpc::ServerContext* /*context*/, const ::realestate::Empty* /*request*/, ::grpc::ServerWriter< ::realestate::Property>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamPropertyListings(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_StreamPropertyUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_StreamPropertyUpdates() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_StreamPropertyUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPropertyUpdates(::grpc::ServerContext* /*context*/, const ::realestate::Empty* /*request*/, ::grpc::ServerWriter< ::realestate::PropertyUpdate>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStreamPropertyUpdates(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamPropertyListings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamPropertyListings() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamPropertyListings(context, request); }));
    }
    ~WithRawCallbackMethod_StreamPropertyListings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPropertyListings(::grpc::ServerContext* /*context*/, const ::realestate::Empty* /*request*/, ::grpc::ServerWriter< ::realestate::Property>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamPropertyListings(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_StreamPropertyUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_StreamPropertyUpdates() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->StreamPropertyUpdates(context, request); }));
    }
    ~WithRawCallbackMethod_StreamPropertyUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status StreamPropertyUpdates(::grpc::ServerContext* /*context*/, const ::realestate::Empty* /*request*/, ::grpc::ServerWriter< ::realestate::PropertyUpdate>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* StreamPropertyUpdates(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamPropertyListings : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamPropertyListings() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::realestate::Empty, ::realestate::Property>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::realestate::Empty, ::realestate::Property>* streamer) {
                       return this->StreamedStreamPropertyListings(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamPropertyListings() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamPropertyListings(::grpc::ServerContext* /*context*/, const ::realestate::Empty* /*request*/, ::grpc::ServerWriter< ::realestate::Property>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamPropertyListings(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::realestate::Empty,::realestate::Property>* server_split_streamer) = 0;
  };
  template <class BaseClass>
  class WithSplitStreamingMethod_StreamPropertyUpdates : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_StreamPropertyUpdates() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::realestate::Empty, ::realestate::PropertyUpdate>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::realestate::Empty, ::realestate::PropertyUpdate>* streamer) {
                       return this->StreamedStreamPropertyUpdates(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_StreamPropertyUpdates() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status StreamPropertyUpdates(::grpc::ServerContext* /*context*/, const ::realestate::Empty* /*request*/, ::grpc::ServerWriter< ::realestate::PropertyUpdate>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedStreamPropertyUpdates(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::realestate::Empty,::realestate::PropertyUpdate>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_StreamPropertyListings<WithSplitStreamingMethod_StreamPropertyUpdates<Service > > SplitStreamedService;
  typedef WithSplitStreamingMethod_StreamPropertyListings<WithSplitStreamingMethod_StreamPropertyUpdates<Service > > StreamedService;
};

}  // namespace realestate


#endif  // GRPC_real_5festate_2eproto__INCLUDED
